// src/utils/downloadHtml.js
export function itineraryTextToHtml(itineraryText, title = "SmartTrip Itinerary") {
  const days = itineraryText
    .split(/\n(?=Day\s+\d+:)/g)
    .map(s => s.trim())
    .filter(Boolean);

  const daySections = days.map((section) => {
    const [firstLine, ...rest] = section.split("\n");
    const body = rest.join("\n")
      .replace(/\n{2,}/g, "\n")          // collapse extra blank lines
      .replace(/\n- /g, "<li>")          // simple list bullets
      .replace(/\n/g, "<br/>");

    // If we used <li>, close them (quick heuristic)
    const ulWrapped = body.includes("<li>")
      ? `<ul style="margin: 0 0 0.25in; padding-left: 0.2in; list-style: disc;">${body.replaceAll("<br/>", "")}</ul>`
      : `<p>${body}</p>`;

    return `
      <section class="day">
        <h2>${firstLine || "Day"}</h2>
        ${ulWrapped}
      </section>
    `;
  }).join("\n");

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${title}</title>
  <style>
    :root {
      --text: #1f2937; /* slate-800 */
      --muted: #6b7280; /* gray-500 */
      --primary: #0ea5e9; /* sky-500 */
      --border: #e5e7eb; /* gray-200 */
    }
    @page { size: A4; margin: 18mm; }
    @media print {
      .no-print { display: none !important; }
      .day { break-inside: avoid-page; page-break-inside: avoid; margin-bottom: 10mm; }
      .day + .day { page-break-before: auto; }
    }
    * { box-sizing: border-box; }
    body {
      font: 14px/1.55 system-ui, -apple-system, Segoe UI, Roboto, Arial, "Noto Sans", "Helvetica Neue", sans-serif;
      color: var(--text);
      background: #fff;
      margin: 0; padding: 0;
    }
    .wrap {
      max-width: 800px;
      margin: 24px auto;
      padding: 24px 28px;
      border: 1px solid var(--border);
      border-radius: 14px;
    }
    h1 {
      margin: 0 0 8px; font-size: 24px; color: var(--primary);
    }
    .meta { color: var(--muted); margin-bottom: 18px; }
    h2 { font-size: 18px; margin: 18px 0 6px; }
    p { margin: 0 0 10px; }
    ul { margin: 0 0 10px 1em; }
    .divider { height: 1px; background: var(--border); margin: 14px 0 18px; }
    .footer { color: var(--muted); font-size: 12px; margin-top: 18px; }
  </style>
</head>
<body>
  <div class="wrap">
    <h1>${title}</h1>
    <div class="meta">Generated by SmartTrip</div>
    <div class="divider"></div>
    ${daySections || "<p>No itinerary content.</p>"}
    <div class="footer">Tip: Open in your browser to print to PDF, or open in Word and Save as PDF/DOCX.</div>
  </div>
</body>
</html>`;
}

export function downloadHtml(filename, htmlString) {
  const blob = new Blob([htmlString], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".html") ? filename : `${filename}.html`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
